/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyConsole */

#ifndef _Included_MyConsole
#define _Included_MyConsole
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyConsole
 * Method:    clearConsole
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MyConsole_clearConsole
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
