/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class phonebook_MyConsole */

#ifndef _Included_phonebook_MyConsole
#define _Included_phonebook_MyConsole
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     phonebook_MyConsole
 * Method:    clearConsole
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_phonebook_MyConsole_clearConsole
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
